"""
data_preprocessing.py
Loads and preprocesses simulation data from MATLAB (simulated OPC-UA data)
Prepares data for anomaly detection

Author: [Your Name]
Date: December 2025
"""

import pandas as pd
import numpy as np
import os

def load_simulation_data(filepath='../data/simulation_output.csv'):
    """
    Load simulation data from CSV file
    
    Args:
        filepath: Path to CSV file generated by MATLAB
        
    Returns:
        DataFrame with simulation data
    """
    print("Loading simulation data...")
    
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Data file not found: {filepath}")
    
    df = pd.read_csv(filepath)
    print(f"Loaded {len(df)} data points")
    print(f"Columns: {list(df.columns)}")
    
    return df

def calculate_derived_features(df):
    """
    Calculate derived features for anomaly detection
    
    Args:
        df: DataFrame with raw simulation data
        
    Returns:
        DataFrame with additional features
    """
    print("\nCalculating derived features...")
    
    # Temperature error (deviation from setpoint)
    df['T_error'] = df['T_reactor_K'] - df['Tsp_setpoint_K']
    
    # Rate of change of reactor temperature (dT/dt)
    df['dT_dt'] = df['T_reactor_K'].diff() / df['Time_min'].diff()
    df['dT_dt'].fillna(0, inplace=True)  # First value is NaN
    
    # Temperature difference between reactor and coolant
    df['delta_T'] = df['T_reactor_K'] - df['T_coolant_K']
    
    # Normalized coolant flow (0 to 1 scale, assuming max is 100 L/min)
    df['Fc_normalized'] = df['Fc_coolant_L_per_min'] / 100.0
    
    # Feed temperature deviation from nominal
    Tf_nominal = df['Tf_feed_K'].iloc[0]  # Assume first value is nominal
    df['Tf_deviation'] = df['Tf_feed_K'] - Tf_nominal
    
    print("Derived features calculated:")
    print("  - T_error: Temperature deviation from setpoint")
    print("  - dT_dt: Rate of temperature change")
    print("  - delta_T: Reactor-coolant temperature difference")
    print("  - Fc_normalized: Normalized coolant flow")
    print("  - Tf_deviation: Feed temperature deviation")
    
    return df

def calculate_rolling_statistics(df, window=20):
    """
    Calculate rolling mean and standard deviation for anomaly detection
    
    Args:
        df: DataFrame with simulation data
        window: Rolling window size (number of samples)
        
    Returns:
        DataFrame with rolling statistics
    """
    print(f"\nCalculating rolling statistics (window={window})...")
    
    # Rolling statistics for reactor temperature
    df['T_rolling_mean'] = df['T_reactor_K'].rolling(window=window, center=True).mean()
    df['T_rolling_std'] = df['T_reactor_K'].rolling(window=window, center=True).std()
    
    # Fill NaN values at edges with overall statistics
    df['T_rolling_mean'].fillna(df['T_reactor_K'].mean(), inplace=True)
    df['T_rolling_std'].fillna(df['T_reactor_K'].std(), inplace=True)
    
    # Calculate z-score (number of standard deviations from mean)
    df['T_zscore'] = (df['T_reactor_K'] - df['T_rolling_mean']) / (df['T_rolling_std'] + 1e-6)
    
    print("Rolling statistics calculated")
    
    return df

def handle_missing_values(df):
    """
    Check for and handle missing values
    
    Args:
        df: DataFrame with simulation data
        
    Returns:
        DataFrame with missing values handled
    """
    print("\nChecking for missing values...")
    
    missing_counts = df.isnull().sum()
    if missing_counts.sum() > 0:
        print("Missing values found:")
        print(missing_counts[missing_counts > 0])
        
        # Forward fill for time-series data
        df.fillna(method='ffill', inplace=True)
        print("Missing values filled using forward fill")
    else:
        print("No missing values found")
    
    return df

def save_preprocessed_data(df, filepath='../data/preprocessed_data.csv'):
    """
    Save preprocessed data to CSV
    
    Args:
        df: DataFrame with preprocessed data
        filepath: Output file path
    """
    print(f"\nSaving preprocessed data to {filepath}...")
    df.to_csv(filepath, index=False)
    print("Preprocessed data saved successfully")

def main():
    """
    Main preprocessing pipeline
    """
    print("="*60)
    print("CSTR Digital Twin - Data Preprocessing")
    print("="*60)
    
    # Load data
    df = load_simulation_data()
    
    # Handle missing values
    df = handle_missing_values(df)
    
    # Calculate derived features
    df = calculate_derived_features(df)
    
    # Calculate rolling statistics
    df = calculate_rolling_statistics(df, window=20)
    
    # Save preprocessed data
    save_preprocessed_data(df)
    
    # Display summary statistics
    print("\n" + "="*60)
    print("Summary Statistics")
    print("="*60)
    print(df[['T_reactor_K', 'T_coolant_K', 'Fc_coolant_L_per_min', 
              'T_error', 'dT_dt']].describe())
    
    print("\n" + "="*60)
    print("Preprocessing complete!")
    print("Next step: Run anomaly_detection.py")
    print("="*60)

if __name__ == "__main__":
    main()
